export default {
    LIST_OBSERVATION: 'LIST_OBSERVATION',
    LIST_OBSERVATION_SUCCESS: 'LIST_OBSERVATION_SUCCESS',
    LIST_OBSERVATION_ERROR: 'LIST_OBSERVATION_ERROR',
    GET_AREA: 'GET_AREA',
    GET_AREA_SUCCESS: 'GET_AREA_SUCCESS',
    GET_SECTION: 'GET_SECTION',
    GET_SECTION_SUCCESS: 'GET_SECTION_SUCCESS',
}